### ISSUE TITLE
Add code preview option.

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#16]
To support #12, add code preview using chrome browser.

Use https://developer.chrome.com/multidevice/android/customtabs

**Comment by amardeshbd** [comment]
![screencast](https://user-images.githubusercontent.com/99822/55640025-c5ff5000-5798-11e9-8e16-c6e8400e4bb1.gif)

**Comment by amardeshbd** [comment]
![screencast](https://user-images.githubusercontent.com/99822/55640296-50e04a80-5799-11e9-9209-01b99e7ddd52.gif)
