### ISSUE TITLE
Add a grid view for the different type of items.

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#2]
Grid view should also contain UI snapshot. Use `GridLayoutManager`

See https://www.journaldev.com/13792/android-gridlayoutmanager-example

**Comment by amardeshbd** [comment]
![demo](https://user-images.githubusercontent.com/99822/39676220-f20ef5c6-5134-11e8-9430-08f90b5fe5fb.png)


Got this far.
