### ISSUE TITLE
Add demo for `ConstraintLayout` feature Margins

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#26]
### Margins

![](https://developer.android.com/reference/android/support/constraint/resources/images/relative-positioning-margin.png)
 
Fig. 3 - Relative Positioning Margins
If side margins are set, they will be applied to the corresponding constraints (if they exist) (Fig. 3), enforcing the margin as a space between the target and the source side. The usual layout margin attributes can be used to this effect:

android:layout_marginStart
android:layout_marginEnd
android:layout_marginLeft
android:layout_marginTop
android:layout_marginRight
android:layout_marginBottom
Note that a margin can only be positive or equals to zero, and takes a Dimension.

Margins when connected to a GONE widget
When a position constraint target's visibility is View.GONE, you can also indicate a different margin value to be used using the following attributes:

layout_goneMarginStart
layout_goneMarginEnd
layout_goneMarginLeft
layout_goneMarginTop
layout_goneMarginRight
layout_goneMarginBottom

**Comment by amardeshbd** [comment]
I think this is a very basic feature, no longer required.
