### ISSUE TITLE
Add demo for `ConstraintLayout` feature minimum dimensions

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#29]
### Minimum dimensions on ConstraintLayout
You can define minimum and maximum sizes for the ConstraintLayout itself:

android:minWidth set the minimum width for the layout
android:minHeight set the minimum height for the layout
android:maxWidth set the maximum width for the layout
android:maxHeight set the maximum height for the layout
Those minimum and maximum dimensions will be used by ConstraintLayout when its dimensions are set to WRAP_CONTENT.

**Comment by amardeshbd** [comment]
Duplicate of #54
