### ISSUE TITLE
Add demo for `ConstraintLayout` feature widgets dimension constraints

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#30]
### Widgets dimension constraints
The dimension of the widgets can be specified by setting the android:layout_width and android:layout_height attributes in 3 different ways:

Using a specific dimension (either a literal value such as 123dp or a Dimension reference)
Using WRAP_CONTENT, which will ask the widget to compute its own size
Using 0dp, which is the equivalent of "MATCH_CONSTRAINT"

![](https://developer.android.com/reference/android/support/constraint/resources/images/dimension-match-constraints.png) 
Fig. 8 - Dimension Constraints

The first two works in a similar fashion as other layouts. The last one will resize the widget in such a way as matching the constraints that are set (see Fig. 8, (a) is wrap_content, (b) is 0dp). If margins are set, they will be taken in account in the computation (Fig. 8, (c) with 0dp).
Important: MATCH_PARENT is not recommended for widgets contained in a ConstraintLayout. Similar behavior can be defined by using MATCH_CONSTRAINT with the corresponding left/right or top/bottom constraints being set to "parent".

**Comment by amardeshbd** [comment]
I think this is a very basic feature, no longer required.
