### ISSUE TITLE
Add demo for `ConstraintLayout` feature for chains with margins

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#48]
## Margins and chains (in 1.1)
When using margins on elements in a chain, the margins are additive.

For example, on a horizontal chain, if one element defines a right margin of 10dp and the next element defines a left margin of 5dp, the resulting margin between those two elements is 15dp.

An item plus its margins are considered together when calculating leftover space used by chains to position items. The leftover space does not contain the margins.

**Comment by amardeshbd** [comment]
A basic feature, not required or could be combined with an existing screen.
